package com.synitl.server.pojo;

// Generated Mar 1, 2015 7:17:14 PM by Hibernate Tools 4.3.1

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer id;
	private String name;
	private String ip;
	private String mac;
	private String uuid;
	private String domain;
	private String ip1;
	private String mac1;
	private String ip2;
	private String mac2;
	private String user;

	public Client() {
	}

	public Client(String name, String ip) {
		this.name = name;
		this.ip = ip;
	}

	public Client(String name, String ip, String mac, String uuid,
			String domain, String ip1, String mac1, String ip2, String mac2,
			String user) {
		this.name = name;
		this.ip = ip;
		this.mac = mac;
		this.uuid = uuid;
		this.domain = domain;
		this.ip1 = ip1;
		this.mac1 = mac1;
		this.ip2 = ip2;
		this.mac2 = mac2;
		this.user = user;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getIp1() {
		return this.ip1;
	}

	public void setIp1(String ip1) {
		this.ip1 = ip1;
	}

	public String getMac1() {
		return this.mac1;
	}

	public void setMac1(String mac1) {
		this.mac1 = mac1;
	}

	public String getIp2() {
		return this.ip2;
	}

	public void setIp2(String ip2) {
		this.ip2 = ip2;
	}

	public String getMac2() {
		return this.mac2;
	}

	public void setMac2(String mac2) {
		this.mac2 = mac2;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
