package com.synitl.server.pojo;

// Generated Feb 27, 2015 6:23:37 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * EnforcerLogsetting generated by hbm2java
 */
@Entity
public class EnforcerLogsetting implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	private Boolean serverLogEnable;
	private Boolean serverLogUpload;
	private Integer serverLogMax;
	private Integer serverLogRecord;
	private Boolean clientLogEnable;
	private Boolean clientLogUpload;
	private Integer clientLogMax;
	private Integer clientLogRecord;
	private Boolean commLogEnable;
	private Boolean commLogUpload;
	private Integer commLogMax;
	private Integer commLogRecord;
	private Integer commLogFilter;
	@OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "id")
	private Set<Gw> gws = new HashSet(0);
	@OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "id")
	private Set<Lan> lans = new HashSet(0);

	public EnforcerLogsetting() {
	}

	public EnforcerLogsetting(Boolean serverLogEnable, Boolean serverLogUpload,
			Integer serverLogMax, Integer serverLogRecord,
			Boolean clientLogEnable, Boolean clientLogUpload,
			Integer clientLogMax, Integer clientLogRecord,
			Boolean commLogEnable, Boolean commLogUpload, Integer commLogMax,
			Integer commLogRecord, Integer commLogFilter, Set gws, Set lans) {
		this.serverLogEnable = serverLogEnable;
		this.serverLogUpload = serverLogUpload;
		this.serverLogMax = serverLogMax;
		this.serverLogRecord = serverLogRecord;
		this.clientLogEnable = clientLogEnable;
		this.clientLogUpload = clientLogUpload;
		this.clientLogMax = clientLogMax;
		this.clientLogRecord = clientLogRecord;
		this.commLogEnable = commLogEnable;
		this.commLogUpload = commLogUpload;
		this.commLogMax = commLogMax;
		this.commLogRecord = commLogRecord;
		this.commLogFilter = commLogFilter;
		this.gws = gws;
		this.lans = lans;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Boolean getServerLogEnable() {
		return this.serverLogEnable;
	}

	public void setServerLogEnable(Boolean serverLogEnable) {
		this.serverLogEnable = serverLogEnable;
	}

	public Boolean getServerLogUpload() {
		return this.serverLogUpload;
	}

	public void setServerLogUpload(Boolean serverLogUpload) {
		this.serverLogUpload = serverLogUpload;
	}

	public Integer getServerLogMax() {
		return this.serverLogMax;
	}

	public void setServerLogMax(Integer serverLogMax) {
		this.serverLogMax = serverLogMax;
	}

	public Integer getServerLogRecord() {
		return this.serverLogRecord;
	}

	public void setServerLogRecord(Integer serverLogRecord) {
		this.serverLogRecord = serverLogRecord;
	}

	public Boolean getClientLogEnable() {
		return this.clientLogEnable;
	}

	public void setClientLogEnable(Boolean clientLogEnable) {
		this.clientLogEnable = clientLogEnable;
	}

	public Boolean getClientLogUpload() {
		return this.clientLogUpload;
	}

	public void setClientLogUpload(Boolean clientLogUpload) {
		this.clientLogUpload = clientLogUpload;
	}

	public Integer getClientLogMax() {
		return this.clientLogMax;
	}

	public void setClientLogMax(Integer clientLogMax) {
		this.clientLogMax = clientLogMax;
	}

	public Integer getClientLogRecord() {
		return this.clientLogRecord;
	}

	public void setClientLogRecord(Integer clientLogRecord) {
		this.clientLogRecord = clientLogRecord;
	}

	public Boolean getCommLogEnable() {
		return this.commLogEnable;
	}

	public void setCommLogEnable(Boolean commLogEnable) {
		this.commLogEnable = commLogEnable;
	}

	public Boolean getCommLogUpload() {
		return this.commLogUpload;
	}

	public void setCommLogUpload(Boolean commLogUpload) {
		this.commLogUpload = commLogUpload;
	}

	public Integer getCommLogMax() {
		return this.commLogMax;
	}

	public void setCommLogMax(Integer commLogMax) {
		this.commLogMax = commLogMax;
	}

	public Integer getCommLogRecord() {
		return this.commLogRecord;
	}

	public void setCommLogRecord(Integer commLogRecord) {
		this.commLogRecord = commLogRecord;
	}

	public Integer getCommLogFilter() {
		return this.commLogFilter;
	}

	public void setCommLogFilter(Integer commLogFilter) {
		this.commLogFilter = commLogFilter;
	}

	public Set getGws() {
		return this.gws;
	}

	public void setGws(Set gws) {
		this.gws = gws;
	}

	public Set getLans() {
		return this.lans;
	}

	public void setLans(Set lans) {
		this.lans = lans;
	}

}
