package com.synitl.server.pojo;

// Generated Mar 1, 2015 7:17:14 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * EnforcerAdvanceSettings generated by hbm2java
 */
public class EnforcerAdvanceSettings implements java.io.Serializable {

	private Integer id;
	private Boolean dhcpIpv4Allow;
	private Boolean dnsIpv4Allow;
	private Boolean arpAllow;
	private Boolean ipv6Allow;
	private Boolean allowNonIpAndNonArp;
	private String filter;
	private Boolean allowLegacyClient;
	private Boolean enableLocalAuth;
	private Boolean enableNtp;
	private String ntpServer;
	private Boolean enableServerCheck;
	private Integer checkInterval;
	private Set gws = new HashSet(0);
	private Set lans = new HashSet(0);

	public EnforcerAdvanceSettings() {
	}

	public EnforcerAdvanceSettings(Boolean dhcpIpv4Allow, Boolean dnsIpv4Allow,
			Boolean arpAllow, Boolean ipv6Allow, Boolean allowNonIpAndNonArp,
			String filter, Boolean allowLegacyClient, Boolean enableLocalAuth,
			Boolean enableNtp, String ntpServer, Boolean enableServerCheck,
			Integer checkInterval, Set gws, Set lans) {
		this.dhcpIpv4Allow = dhcpIpv4Allow;
		this.dnsIpv4Allow = dnsIpv4Allow;
		this.arpAllow = arpAllow;
		this.ipv6Allow = ipv6Allow;
		this.allowNonIpAndNonArp = allowNonIpAndNonArp;
		this.filter = filter;
		this.allowLegacyClient = allowLegacyClient;
		this.enableLocalAuth = enableLocalAuth;
		this.enableNtp = enableNtp;
		this.ntpServer = ntpServer;
		this.enableServerCheck = enableServerCheck;
		this.checkInterval = checkInterval;
		this.gws = gws;
		this.lans = lans;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Boolean getDhcpIpv4Allow() {
		return this.dhcpIpv4Allow;
	}

	public void setDhcpIpv4Allow(Boolean dhcpIpv4Allow) {
		this.dhcpIpv4Allow = dhcpIpv4Allow;
	}

	public Boolean getDnsIpv4Allow() {
		return this.dnsIpv4Allow;
	}

	public void setDnsIpv4Allow(Boolean dnsIpv4Allow) {
		this.dnsIpv4Allow = dnsIpv4Allow;
	}

	public Boolean getArpAllow() {
		return this.arpAllow;
	}

	public void setArpAllow(Boolean arpAllow) {
		this.arpAllow = arpAllow;
	}

	public Boolean getIpv6Allow() {
		return this.ipv6Allow;
	}

	public void setIpv6Allow(Boolean ipv6Allow) {
		this.ipv6Allow = ipv6Allow;
	}

	public Boolean getAllowNonIpAndNonArp() {
		return this.allowNonIpAndNonArp;
	}

	public void setAllowNonIpAndNonArp(Boolean allowNonIpAndNonArp) {
		this.allowNonIpAndNonArp = allowNonIpAndNonArp;
	}

	public String getFilter() {
		return this.filter;
	}

	public void setFilter(String filter) {
		this.filter = filter;
	}

	public Boolean getAllowLegacyClient() {
		return this.allowLegacyClient;
	}

	public void setAllowLegacyClient(Boolean allowLegacyClient) {
		this.allowLegacyClient = allowLegacyClient;
	}

	public Boolean getEnableLocalAuth() {
		return this.enableLocalAuth;
	}

	public void setEnableLocalAuth(Boolean enableLocalAuth) {
		this.enableLocalAuth = enableLocalAuth;
	}

	public Boolean getEnableNtp() {
		return this.enableNtp;
	}

	public void setEnableNtp(Boolean enableNtp) {
		this.enableNtp = enableNtp;
	}

	public String getNtpServer() {
		return this.ntpServer;
	}

	public void setNtpServer(String ntpServer) {
		this.ntpServer = ntpServer;
	}

	public Boolean getEnableServerCheck() {
		return this.enableServerCheck;
	}

	public void setEnableServerCheck(Boolean enableServerCheck) {
		this.enableServerCheck = enableServerCheck;
	}

	public Integer getCheckInterval() {
		return this.checkInterval;
	}

	public void setCheckInterval(Integer checkInterval) {
		this.checkInterval = checkInterval;
	}

	public Set getGws() {
		return this.gws;
	}

	public void setGws(Set gws) {
		this.gws = gws;
	}

	public Set getLans() {
		return this.lans;
	}

	public void setLans(Set lans) {
		this.lans = lans;
	}

}
