package com.synitl.server.pojo;

// Generated Mar 1, 2015 7:17:14 PM by Hibernate Tools 4.3.1

/**
 * ExchangeAction generated by hbm2java
 */
public class ExchangeAction implements java.io.Serializable {

	private Integer id;
	private ExchangePolicy exchangePolicy;
	private int seq;
	private Boolean hiStatus;
	private Boolean userAuth;
	private Boolean policyCheck;
	private int action;

	public ExchangeAction() {
	}

	public ExchangeAction(ExchangePolicy exchangePolicy, int seq, int action) {
		this.exchangePolicy = exchangePolicy;
		this.seq = seq;
		this.action = action;
	}

	public ExchangeAction(ExchangePolicy exchangePolicy, int seq,
			Boolean hiStatus, Boolean userAuth, Boolean policyCheck, int action) {
		this.exchangePolicy = exchangePolicy;
		this.seq = seq;
		this.hiStatus = hiStatus;
		this.userAuth = userAuth;
		this.policyCheck = policyCheck;
		this.action = action;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ExchangePolicy getExchangePolicy() {
		return this.exchangePolicy;
	}

	public void setExchangePolicy(ExchangePolicy exchangePolicy) {
		this.exchangePolicy = exchangePolicy;
	}

	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	public Boolean getHiStatus() {
		return this.hiStatus;
	}

	public void setHiStatus(Boolean hiStatus) {
		this.hiStatus = hiStatus;
	}

	public Boolean getUserAuth() {
		return this.userAuth;
	}

	public void setUserAuth(Boolean userAuth) {
		this.userAuth = userAuth;
	}

	public Boolean getPolicyCheck() {
		return this.policyCheck;
	}

	public void setPolicyCheck(Boolean policyCheck) {
		this.policyCheck = policyCheck;
	}

	public int getAction() {
		return this.action;
	}

	public void setAction(int action) {
		this.action = action;
	}

}
