package com.synitl.server.pojo;

// Generated Feb 27, 2015 6:23:37 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * ExchangePolicy generated by hbm2java
 */
@Entity
public class ExchangePolicy implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	private Lan lan;
	private String name;
	private Boolean enabled;
	private String model;
	private String ip;
	private int seq;
	@OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "id")
	private Set<ExchangeAction> exchangeActions = new HashSet(0);

	public ExchangePolicy() {
	}

	public ExchangePolicy(Lan lan, String name, int seq) {
		this.lan = lan;
		this.name = name;
		this.seq = seq;
	}

	public ExchangePolicy(Lan lan, String name, Boolean enabled, String model,
			String ip, int seq, Set exchangeActions) {
		this.lan = lan;
		this.name = name;
		this.enabled = enabled;
		this.model = model;
		this.ip = ip;
		this.seq = seq;
		this.exchangeActions = exchangeActions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Lan getLan() {
		return this.lan;
	}

	public void setLan(Lan lan) {
		this.lan = lan;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	public Set getExchangeActions() {
		return this.exchangeActions;
	}

	public void setExchangeActions(Set exchangeActions) {
		this.exchangeActions = exchangeActions;
	}

}
