package com.synitl.server.pojo;

// Generated Mar 1, 2015 7:17:14 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Gw generated by hbm2java
 */
public class Gw implements java.io.Serializable {

	private Integer id;
	private EnforcerAdvanceSettings enforcerAdvanceSettings;
	private EnforcerLogsetting enforcerLogsetting;
	private GwValidateRange gwValidateRange;
	private Integer maxPackageEachValidation;
	private Integer intervalDuringValidation;
	private Integer timeToBlockClient;
	private Integer allowTrustedClient;
	private Boolean allowTrustedButRecordUntrusted;
	private Boolean nonHiForNonWindows;
	private Boolean policySerialNumberFirst;
	private Boolean popupForWindowsWithoutClient;
	private String popupMessage;
	private Boolean httpRedirectWithoutClient;
	private String httpRedirectUrl;
	private Integer httpRedirectPort;
	private int enabled;
	private String name;
	private String description;
	private Date creationTime;
	private Date lastUpdateTime;

	public Gw() {
	}

	public Gw(EnforcerAdvanceSettings enforcerAdvanceSettings,
			EnforcerLogsetting enforcerLogsetting,
			GwValidateRange gwValidateRange, int enabled, String name,
			String description, Date creationTime, Date lastUpdateTime) {
		this.enforcerAdvanceSettings = enforcerAdvanceSettings;
		this.enforcerLogsetting = enforcerLogsetting;
		this.gwValidateRange = gwValidateRange;
		this.enabled = enabled;
		this.name = name;
		this.description = description;
		this.creationTime = creationTime;
		this.lastUpdateTime = lastUpdateTime;
	}

	public Gw(EnforcerAdvanceSettings enforcerAdvanceSettings,
			EnforcerLogsetting enforcerLogsetting,
			GwValidateRange gwValidateRange, Integer maxPackageEachValidation,
			Integer intervalDuringValidation, Integer timeToBlockClient,
			Integer allowTrustedClient, Boolean allowTrustedButRecordUntrusted,
			Boolean nonHiForNonWindows, Boolean policySerialNumberFirst,
			Boolean popupForWindowsWithoutClient, String popupMessage,
			Boolean httpRedirectWithoutClient, String httpRedirectUrl,
			Integer httpRedirectPort, int enabled, String name,
			String description, Date creationTime, Date lastUpdateTime) {
		this.enforcerAdvanceSettings = enforcerAdvanceSettings;
		this.enforcerLogsetting = enforcerLogsetting;
		this.gwValidateRange = gwValidateRange;
		this.maxPackageEachValidation = maxPackageEachValidation;
		this.intervalDuringValidation = intervalDuringValidation;
		this.timeToBlockClient = timeToBlockClient;
		this.allowTrustedClient = allowTrustedClient;
		this.allowTrustedButRecordUntrusted = allowTrustedButRecordUntrusted;
		this.nonHiForNonWindows = nonHiForNonWindows;
		this.policySerialNumberFirst = policySerialNumberFirst;
		this.popupForWindowsWithoutClient = popupForWindowsWithoutClient;
		this.popupMessage = popupMessage;
		this.httpRedirectWithoutClient = httpRedirectWithoutClient;
		this.httpRedirectUrl = httpRedirectUrl;
		this.httpRedirectPort = httpRedirectPort;
		this.enabled = enabled;
		this.name = name;
		this.description = description;
		this.creationTime = creationTime;
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public EnforcerAdvanceSettings getEnforcerAdvanceSettings() {
		return this.enforcerAdvanceSettings;
	}

	public void setEnforcerAdvanceSettings(
			EnforcerAdvanceSettings enforcerAdvanceSettings) {
		this.enforcerAdvanceSettings = enforcerAdvanceSettings;
	}

	public EnforcerLogsetting getEnforcerLogsetting() {
		return this.enforcerLogsetting;
	}

	public void setEnforcerLogsetting(EnforcerLogsetting enforcerLogsetting) {
		this.enforcerLogsetting = enforcerLogsetting;
	}

	public GwValidateRange getGwValidateRange() {
		return this.gwValidateRange;
	}

	public void setGwValidateRange(GwValidateRange gwValidateRange) {
		this.gwValidateRange = gwValidateRange;
	}

	public Integer getMaxPackageEachValidation() {
		return this.maxPackageEachValidation;
	}

	public void setMaxPackageEachValidation(Integer maxPackageEachValidation) {
		this.maxPackageEachValidation = maxPackageEachValidation;
	}

	public Integer getIntervalDuringValidation() {
		return this.intervalDuringValidation;
	}

	public void setIntervalDuringValidation(Integer intervalDuringValidation) {
		this.intervalDuringValidation = intervalDuringValidation;
	}

	public Integer getTimeToBlockClient() {
		return this.timeToBlockClient;
	}

	public void setTimeToBlockClient(Integer timeToBlockClient) {
		this.timeToBlockClient = timeToBlockClient;
	}

	public Integer getAllowTrustedClient() {
		return this.allowTrustedClient;
	}

	public void setAllowTrustedClient(Integer allowTrustedClient) {
		this.allowTrustedClient = allowTrustedClient;
	}

	public Boolean getAllowTrustedButRecordUntrusted() {
		return this.allowTrustedButRecordUntrusted;
	}

	public void setAllowTrustedButRecordUntrusted(
			Boolean allowTrustedButRecordUntrusted) {
		this.allowTrustedButRecordUntrusted = allowTrustedButRecordUntrusted;
	}

	public Boolean getNonHiForNonWindows() {
		return this.nonHiForNonWindows;
	}

	public void setNonHiForNonWindows(Boolean nonHiForNonWindows) {
		this.nonHiForNonWindows = nonHiForNonWindows;
	}

	public Boolean getPolicySerialNumberFirst() {
		return this.policySerialNumberFirst;
	}

	public void setPolicySerialNumberFirst(Boolean policySerialNumberFirst) {
		this.policySerialNumberFirst = policySerialNumberFirst;
	}

	public Boolean getPopupForWindowsWithoutClient() {
		return this.popupForWindowsWithoutClient;
	}

	public void setPopupForWindowsWithoutClient(
			Boolean popupForWindowsWithoutClient) {
		this.popupForWindowsWithoutClient = popupForWindowsWithoutClient;
	}

	public String getPopupMessage() {
		return this.popupMessage;
	}

	public void setPopupMessage(String popupMessage) {
		this.popupMessage = popupMessage;
	}

	public Boolean getHttpRedirectWithoutClient() {
		return this.httpRedirectWithoutClient;
	}

	public void setHttpRedirectWithoutClient(Boolean httpRedirectWithoutClient) {
		this.httpRedirectWithoutClient = httpRedirectWithoutClient;
	}

	public String getHttpRedirectUrl() {
		return this.httpRedirectUrl;
	}

	public void setHttpRedirectUrl(String httpRedirectUrl) {
		this.httpRedirectUrl = httpRedirectUrl;
	}

	public Integer getHttpRedirectPort() {
		return this.httpRedirectPort;
	}

	public void setHttpRedirectPort(Integer httpRedirectPort) {
		this.httpRedirectPort = httpRedirectPort;
	}

	public int getEnabled() {
		return this.enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

}
