package com.synitl.server.pojo;

// Generated Feb 27, 2015 6:23:37 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * GwValidateIpRange generated by hbm2java
 */
@Entity
public class GwValidateIpRange implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	private int seq;
	private Boolean enable;
	private String ip;
	@OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "id")
	private Set<GwValidateRange> gwValidateRangesForTrustIpRange = new HashSet(0);
	@OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "id")
	private Set<GwValidateRange> gwValidateRangesForValidateIpReange = new HashSet(0);

	public GwValidateIpRange() {
	}

	public GwValidateIpRange(int seq) {
		this.seq = seq;
	}

	public GwValidateIpRange(int seq, Boolean enable, String ip,
			Set gwValidateRangesForTrustIpRange,
			Set gwValidateRangesForValidateIpReange) {
		this.seq = seq;
		this.enable = enable;
		this.ip = ip;
		this.gwValidateRangesForTrustIpRange = gwValidateRangesForTrustIpRange;
		this.gwValidateRangesForValidateIpReange = gwValidateRangesForValidateIpReange;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	public Boolean getEnable() {
		return this.enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Set getGwValidateRangesForTrustIpRange() {
		return this.gwValidateRangesForTrustIpRange;
	}

	public void setGwValidateRangesForTrustIpRange(
			Set gwValidateRangesForTrustIpRange) {
		this.gwValidateRangesForTrustIpRange = gwValidateRangesForTrustIpRange;
	}

	public Set getGwValidateRangesForValidateIpReange() {
		return this.gwValidateRangesForValidateIpReange;
	}

	public void setGwValidateRangesForValidateIpReange(
			Set gwValidateRangesForValidateIpReange) {
		this.gwValidateRangesForValidateIpReange = gwValidateRangesForValidateIpReange;
	}

}
