package com.synitl.server.pojo;

// Generated Feb 27, 2015 6:23:37 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * GwValidateRange generated by hbm2java
 */
@Entity
public class GwValidateRange implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	private GwValidateIpRange gwValidateIpRangeByTrustIpRange;
	private GwValidateIpRange gwValidateIpRangeByValidateIpReange;
	private Boolean selectiveValidation;
	private int trustIpRangeIndex;
	@OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "id")
	private Set<Gw> gws = new HashSet(0);

	public GwValidateRange() {
	}

	public GwValidateRange(GwValidateIpRange gwValidateIpRangeByTrustIpRange,
			GwValidateIpRange gwValidateIpRangeByValidateIpReange,
			int trustIpRangeIndex) {
		this.gwValidateIpRangeByTrustIpRange = gwValidateIpRangeByTrustIpRange;
		this.gwValidateIpRangeByValidateIpReange = gwValidateIpRangeByValidateIpReange;
		this.trustIpRangeIndex = trustIpRangeIndex;
	}

	public GwValidateRange(GwValidateIpRange gwValidateIpRangeByTrustIpRange,
			GwValidateIpRange gwValidateIpRangeByValidateIpReange,
			Boolean selectiveValidation, int trustIpRangeIndex, Set gws) {
		this.gwValidateIpRangeByTrustIpRange = gwValidateIpRangeByTrustIpRange;
		this.gwValidateIpRangeByValidateIpReange = gwValidateIpRangeByValidateIpReange;
		this.selectiveValidation = selectiveValidation;
		this.trustIpRangeIndex = trustIpRangeIndex;
		this.gws = gws;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public GwValidateIpRange getGwValidateIpRangeByTrustIpRange() {
		return this.gwValidateIpRangeByTrustIpRange;
	}

	public void setGwValidateIpRangeByTrustIpRange(
			GwValidateIpRange gwValidateIpRangeByTrustIpRange) {
		this.gwValidateIpRangeByTrustIpRange = gwValidateIpRangeByTrustIpRange;
	}

	public GwValidateIpRange getGwValidateIpRangeByValidateIpReange() {
		return this.gwValidateIpRangeByValidateIpReange;
	}

	public void setGwValidateIpRangeByValidateIpReange(
			GwValidateIpRange gwValidateIpRangeByValidateIpReange) {
		this.gwValidateIpRangeByValidateIpReange = gwValidateIpRangeByValidateIpReange;
	}

	public Boolean getSelectiveValidation() {
		return this.selectiveValidation;
	}

	public void setSelectiveValidation(Boolean selectiveValidation) {
		this.selectiveValidation = selectiveValidation;
	}

	public int getTrustIpRangeIndex() {
		return this.trustIpRangeIndex;
	}

	public void setTrustIpRangeIndex(int trustIpRangeIndex) {
		this.trustIpRangeIndex = trustIpRangeIndex;
	}

	public Set getGws() {
		return this.gws;
	}

	public void setGws(Set gws) {
		this.gws = gws;
	}

}
