package com.synitl.server.pojo;

// Generated Mar 1, 2015 7:17:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lan generated by hbm2java
 */
public class Lan implements java.io.Serializable {

	private Integer id;
	private EnforcerAdvanceSettings enforcerAdvanceSettings;
	private EnforcerLogsetting enforcerLogsetting;
	private Radiusgroup radiusgroup;
	private int exchangepolicyId;
	private String name;
	private String description;
	private Date creationTime;
	private Date lastUpdateTime;
	private Set exchangePolicies = new HashSet(0);

	public Lan() {
	}

	public Lan(EnforcerAdvanceSettings enforcerAdvanceSettings,
			EnforcerLogsetting enforcerLogsetting, Radiusgroup radiusgroup,
			int exchangepolicyId, String name, String description,
			Date creationTime, Date lastUpdateTime) {
		this.enforcerAdvanceSettings = enforcerAdvanceSettings;
		this.enforcerLogsetting = enforcerLogsetting;
		this.radiusgroup = radiusgroup;
		this.exchangepolicyId = exchangepolicyId;
		this.name = name;
		this.description = description;
		this.creationTime = creationTime;
		this.lastUpdateTime = lastUpdateTime;
	}

	public Lan(EnforcerAdvanceSettings enforcerAdvanceSettings,
			EnforcerLogsetting enforcerLogsetting, Radiusgroup radiusgroup,
			int exchangepolicyId, String name, String description,
			Date creationTime, Date lastUpdateTime, Set exchangePolicies) {
		this.enforcerAdvanceSettings = enforcerAdvanceSettings;
		this.enforcerLogsetting = enforcerLogsetting;
		this.radiusgroup = radiusgroup;
		this.exchangepolicyId = exchangepolicyId;
		this.name = name;
		this.description = description;
		this.creationTime = creationTime;
		this.lastUpdateTime = lastUpdateTime;
		this.exchangePolicies = exchangePolicies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public EnforcerAdvanceSettings getEnforcerAdvanceSettings() {
		return this.enforcerAdvanceSettings;
	}

	public void setEnforcerAdvanceSettings(
			EnforcerAdvanceSettings enforcerAdvanceSettings) {
		this.enforcerAdvanceSettings = enforcerAdvanceSettings;
	}

	public EnforcerLogsetting getEnforcerLogsetting() {
		return this.enforcerLogsetting;
	}

	public void setEnforcerLogsetting(EnforcerLogsetting enforcerLogsetting) {
		this.enforcerLogsetting = enforcerLogsetting;
	}

	public Radiusgroup getRadiusgroup() {
		return this.radiusgroup;
	}

	public void setRadiusgroup(Radiusgroup radiusgroup) {
		this.radiusgroup = radiusgroup;
	}

	public int getExchangepolicyId() {
		return this.exchangepolicyId;
	}

	public void setExchangepolicyId(int exchangepolicyId) {
		this.exchangepolicyId = exchangepolicyId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Set getExchangePolicies() {
		return this.exchangePolicies;
	}

	public void setExchangePolicies(Set exchangePolicies) {
		this.exchangePolicies = exchangePolicies;
	}

}
