package com.synitl.server.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


// Generated Feb 27, 2015 6:23:37 AM by Hibernate Tools 4.3.1

/**
 * ManageServer generated by hbm2java
 */
@Entity
@Table(name = "manage_server")
public class ManageServer implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	private String name;
	private String ip;
	private String description;

	public ManageServer() {
	}

	public ManageServer(String name, String ip, String description) {
		this.name = name;
		this.ip = ip;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
