package com.synitl.server.pojo;

// Generated Mar 1, 2015 7:17:14 PM by Hibernate Tools 4.3.1

/**
 * ManageServer generated by hbm2java
 */
public class ManageServer implements java.io.Serializable {

	private Integer id;
	private String name;
	private String ip;
	private String description;

	public ManageServer() {
	}

	public ManageServer(String name, String ip, String description) {
		this.name = name;
		this.ip = ip;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
