package com.synitl.server.pojo;

// Generated Feb 27, 2015 6:23:37 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Radiusgroup generated by hbm2java
 */
@Entity
public class Radiusgroup implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	private Boolean nps;
	@OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "id")
	private Set<Radius> radiuses = new HashSet(0);
	@OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "id")
	private Set<Lan> lans = new HashSet(0);

	public Radiusgroup() {
	}

	public Radiusgroup(Boolean nps, Set radiuses, Set lans) {
		this.nps = nps;
		this.radiuses = radiuses;
		this.lans = lans;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Boolean getNps() {
		return this.nps;
	}

	public void setNps(Boolean nps) {
		this.nps = nps;
	}

	public Set getRadiuses() {
		return this.radiuses;
	}

	public void setRadiuses(Set radiuses) {
		this.radiuses = radiuses;
	}

	public Set getLans() {
		return this.lans;
	}

	public void setLans(Set lans) {
		this.lans = lans;
	}

}
