package com.synitl.server.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

// Generated Feb 27, 2015 6:23:37 AM by Hibernate Tools 4.3.1

/**
 * Radius generated by hbm2java
 */
@Entity
public class Radius implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	private Radiusgroup radiusgroup;
	private String name;
	private String server;

	public Radius() {
	}

	public Radius(Radiusgroup radiusgroup, String name, String server) {
		this.radiusgroup = radiusgroup;
		this.name = name;
		this.server = server;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Radiusgroup getRadiusgroup() {
		return this.radiusgroup;
	}

	public void setRadiusgroup(Radiusgroup radiusgroup) {
		this.radiusgroup = radiusgroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getServer() {
		return this.server;
	}

	public void setServer(String server) {
		this.server = server;
	}

}
